apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanakana-portfolio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanakana-portfolio
  template:
    metadata:
      labels:
        app: kanakana-portfolio
    spec:
      containers:
      - name: kanakana-portfolio-container
        command: ["npm"]
        
        # ğŸ’¥ å®Ÿè¡Œå¼•æ•°ï¼ˆCMDã‚’ä¸Šæ›¸ãï¼‰
        args: ["run", "dev"]
        image: kanakana-portfolio
        imagePullPolicy: Never
        env:
        - name: COMMAND    # æ¸¡ã—ãŸã„ç’°å¢ƒå¤‰æ•°ã®åå‰
          value: "dev"
        ports:
        - containerPort: 3000